scratchtester/scratchtester/urls.py
from django.contrib import admin
from django.urls import path

from scratchtester import views, consumer

app_name = "scratchtester"
urlpatterns = [
    path("", views.MainPage.as_view()),
    path(
        "measurement/<int:id>/tabbed",
        views.MeasurementTabbed.as_view(),
        name="measurmenttabbed",
    ),
    path(
        "measurement/<int:id>/<option>",
        views.MeasurementView.as_view(),
        name="measurment",
    ),
    path("measurement/<int:id>/<data>", views.MeasurementView.as_view(), name="image"),
    path("data/<int:id>/<data>", views.MeasurementData.as_view(), name="get_data"),
    path("data/<int:id>/<data>", views.MeasurementData.as_view(), name="post_data"),
]

websockets = [path("ws", consumer.BaseConsumer)]

scratchtester/scratchtester/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField


class CsvStructure(models.Model):
    name = models.fields.CharField(max_length=20)
    html = models.fields.CharField(max_length=255, null=True)


class Measurement(models.Model):
    name = models.fields.CharField(max_length=20, default="new_measurment")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    raw_data = models.fields.FilePathField(default=None, null=True)
    raw_structure = models.ForeignKey(
        CsvStructure,
        on_delete=models.SET_DEFAULT,
        default=CsvStructure.objects.get_or_create(name="YZYZ")[0],
    )
    options = models.fields.CharField(max_length=400, default="{}")

scratchtester/scratchtester/views.py
import os

from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View
from djangobase.jsonconfig import JsonConfig

from scratchtester.models import Measurement, CsvStructure
from scratch_reader import ScratchReader
from settings import MEDIA_ROOT


class MainPage(View):
    def get(self, request):
        data = {"measurements": Measurement.objects.all()}
        return render(request, "main.html", data)


class MeasurementTabbed(View):
    def get(self, request, id):
        measurement = Measurement.objects.get(id=id)
        measurement.options = JsonConfig(data=measurement.options)
        data = {"measurement": measurement, "csv_strucs": CsvStructure.objects.all()}
        return render(request, "measurment_tabbed.html", data)


class MeasurementView(View):
    siteorder = [
        "start",
        "structure",
        "interpolation",
        "correction",
        "correction",
        "3d",
    ]

    def get(self, request, id, option):
        if id == 0:
            measurement = Measurement.objects.create()
            return self.get(request, measurement.id, "start")

        measurement = Measurement.objects.get(id=id)
        measurement.options = JsonConfig(data=measurement.options)
        data = {"measurement": measurement, "csv_strucs": CsvStructure.objects.all()}
        return render(request, "measurment_" + option + ".html", data)

    def post(self, request, id, option):
        measurement = Measurement.objects.get(id=id)
        measurement.options = JsonConfig(data=measurement.options)

        recalc = False
        if "name" in request.POST:
            measurement.name = request.POST.get("name", measurement.name)
        if "raw_data" in request.FILES:
            myfile = request.FILES["raw_data"]
            fs = FileSystemStorage(os.path.join(MEDIA_ROOT, "raw"))
            filename = fs.save(myfile.name, myfile)
            print(filename)
            measurement.raw_data = filename
            recalc = True

        if "raw_structure" in request.POST:
            if measurement.raw_structure.id != int(request.POST["raw_structure"]):
                print(
                    "B",
                    measurement.raw_structure.id,
                    request.POST["raw_structure"],
                    measurement.raw_structure.id != request.POST["raw_structure"],
                )
                recalc = True
                measurement.raw_structure = CsvStructure.objects.get(
                    id=request.POST["raw_structure"]
                )

        if not os.path.exists(
            os.path.join(MEDIA_ROOT, "interpolated", measurement.raw_data)
        ):
            recalc = True

        sr = ScratchReader(options=measurement.options)
        for k, v in request.POST.items():
            if k.startswith("opt_"):
                l = k[4:].split(",")
                if l[0] == "interpolation":
                    v, n = measurement.options.put(*l, value=v, testtype=True)
                    recalc = recalc or n
        if recalc:
            sr.read_raw(
                os.path.join(MEDIA_ROOT, "raw", measurement.raw_data),
                structure=measurement.raw_structure.name,
            )
            sr.interpolate()
            sr.save_interpolated(
                os.path.join(MEDIA_ROOT, "interpolated", measurement.raw_data)
            )

        measurement.options = measurement.options.to_json()
        measurement.save()

        return redirect(
            "scratchtester:measurment",
            id=measurement.id,
            option=self.siteorder[self.siteorder.index(option) + 1],
        )


class MeasurementData(View):
    def post(self, request, id, data):
        measurement = Measurement.objects.get(id=id)
        measurement.options = JsonConfig(data=measurement.options)
        if data == "raw":
            myfile = request.FILES["raw_data"]
            fs = FileSystemStorage(os.path.join(MEDIA_ROOT, "raw"))
            fs.delete(measurement.raw_data)
            measurement.raw_data = fs.save(myfile.name, myfile)

        measurement.options = measurement.options.to_json()
        measurement.save()
        return JsonResponse({"success": True})

scratchtester/scratchtester/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{csrf_token}}">

    <title>{% config_get "site,title" %} - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0-rc.2/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<main role="main" class="container">
    {% block content %}{% endblock %}
</main>
</div>



<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0-rc.2/jquery-ui.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% block jsf %}
{% endblock %}
<script>
    $(document).ready(function() {
        {% block js %}{% endblock %}
    });
</script>
</body>
</html>

scratchtester/scratchtester/templates/main.html
{% extends "base.html" %}
{% block title %}main{% endblock %}
{% block content %}
    <a href="{% url "scratchtester:measurment" id=0 option="start"%}">new</a>
    <table>
    {% for ex in experiments %}
        <tr><td>{{ ex.title}}</td></tr>
    {% endfor %}
    </table>
{% endblock %}

scratchtester/scratchtester/templates/measurment_.html
{% extends "base.html" %}

{% block content %}
    {% block m_content %}

    {% endblock %}
{% endblock %}

scratchtester/scratchtester/templates/measurment_correction.html
{% extends "measurment_.html" %}

{% block m_content %}
    <image src="{% url "scratchtester:image" id=measurement.id data='interpolated'%}"></image>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <select id="select_interpolation" name="opt_interpolation,method">
            <option value="nearest" {% if measurement.options|get_item:"interpolation,method" is "nearest" %}selected{% endif %}>nearest</option>
            <option value="linear" {% if measurement.options|get_item:"interpolation,method" is "linear" %}selected{% endif %}>linear</option>

        </select>
        <input type="number" name="opt_interpolation,resolution" value="{{ measurement.options|get_item:"interpolation,resolution" }}">

        <div>
            <table id="raw_structure_example"></table>
        </div>
        <input type="submit" value="Next">
    </form>
{% endblock %}


{% block js %}
{% endblock %}

scratchtester/scratchtester/templates/measurment_interpolation.html
{% extends "measurment_.html" %}

{% block m_content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <select id="select_interpolation" name="opt_interpolation,method">
            <option value="nearest" {% if measurement.options|get_item:"interpolation,method" is "nearest" %}selected{% endif %}>nearest</option>
            <option value="linear" {% if measurement.options|get_item:"interpolation,method" is "linear" %}selected{% endif %}>linear</option>

        </select>
        <input type="number" name="opt_interpolation,resolution" value="{{ measurement.options|get_item:"interpolation,resolution" }}">

        <div>
            <table id="raw_structure_example"></table>
        </div>
        <input type="submit" value="Next">
    </form>
{% endblock %}


{% block js %}
{% endblock %}

scratchtester/scratchtester/templates/measurment_start.html
{% extends "measurment_.html" %}

{% block m_content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
    <input name="name" value="{{ measurement.name }}"/>
        <input name="raw_data" type="file" size="50" accept="text/*">
        <input type="submit" value="Next">
    </form>
{% endblock %}

scratchtester/scratchtester/templates/measurment_structure.html
{% extends "measurment_.html" %}

{% block m_content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <select id="select_raw_structure" name="raw_structure" onchange="raw_struc_change()">
            {% for rs in csv_strucs %}
                <option value={{ rs.id }} {% if measurement.raw_structure.id == rs.id %} selected{% endif %}>{{ rs.name }}</option>
            {% endfor %}
        </select>

        <div>
            <table id="raw_structure_example"></table>
        </div>
        <input type="submit" value="Next">
    </form>
{% endblock %}


{% block js %}
    var raw_struc_options_html = {};
    {% for rs in csv_strucs %}
        raw_struc_options_html[{{rs.id}}] = "{{ rs.html|safe }}";
    {% endfor %}

    window.raw_struc_change = function () {
    document.getElementById("raw_structure_example").innerHTML = raw_struc_options_html[document.getElementById("select_raw_structure").value];
    };
    window.raw_struc_change();
{% endblock %}

scratchtester/scratchtester/templates/measurment_tabbed.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <ul id="myTab" class="nav nav-tabs">
        <li class="nav-item">
            <a data-toggle="tab"  class="nav-link" href="#raw_data" role="tab" aria-controls="raw_data" aria-selected="true">
                Raw data
            </a
            ></li>
        <li class="nav-item">
            <a data-toggle="tab" class="nav-link" href="#interpolation" role="tab" aria-controls="interpolation" aria-selected="false">
                Interpolation
            </a>
        </li>
    </ul>

    <div class="tab-content">
        <div id="raw_data" class="tab-pane fade active show" role="tabpanel" aria-labelledby="raw_data-tab">
            <h3>Raw data</h3>
            <form id="raw_data_form" enctype="multipart/form-data">
                <input name="raw_data" type="file" size="50" accept="text/*">
                <input name="raw_data_n" type="text">

                <button onclick="upload_raw()" type="button">upload</button>
            </form>
        </div>
        <div id="interpolation" class="tab-pane fade" role="tabpanel" aria-labelledby="interpolation-tab">
            <h3>Menu 2</h3>
            <p>Some content in menu 2.</p>
        </div>
    </div>
    <div id="permacontent">
    <div id="progressbar"></div>
    </div>
{% endblock %}


{% block jsf %}
    <script src="{% static "js/scratchtester.js" %}"></script>
{% endblock %}
{% block js %}
    window.raw_data_link = '{% url "scratchtester:get_data" id=measurement.id data="raw" %}'
    window.raw_data_post = '{% url "scratchtester:post_data" id=measurement.id data="raw" %}'
{% endblock %}